//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.WEB.RY.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_TYPE
    {
        public PAGE_TYPE()
        {
            this.PAGE_CONTENT = new HashSet<PAGE_CONTENT>();
        }
    
        public int AUTO_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<PAGE_CONTENT> PAGE_CONTENT { get; set; }
    }
}
