//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.WEB.RY.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_CONTENT
    {
        public PAGE_CONTENT()
        {
            this.PAGE_CUSTOMER = new HashSet<PAGE_CUSTOMER>();
        }
    
        public int AUTO_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public string SECTION_NAME { get; set; }
        public string HTML_SUB_HEADER1 { get; set; }
        public string HTML_SUB_HEADER2 { get; set; }
        public string HTML_VALUE { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<int> SEQ { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual PAGE_TYPE PAGE_TYPE { get; set; }
        public virtual ICollection<PAGE_CUSTOMER> PAGE_CUSTOMER { get; set; }
    }
}
