//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.WEB.RY.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_CUSTOMER
    {
        public int AUTO_ID { get; set; }
        public Nullable<int> PAGE_CONTENT_ID { get; set; }
        public string NAME { get; set; }
        public string LOGO_URL { get; set; }
    
        public virtual PAGE_CONTENT PAGE_CONTENT { get; set; }
    }
}
