//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.WEB.RY.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BIG.WEB.RY.MODEL;
    
    
    public partial class BIG_RY_DBEntities : DbContext
    {
        public BIG_RY_DBEntities()
            : base("name=BIG_RY_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<LOGON> LOGONs { get; set; }
        public DbSet<PAGE_CONTENT> PAGE_CONTENT { get; set; }
        public DbSet<PAGE_CUSTOMER> PAGE_CUSTOMER { get; set; }
        public DbSet<PAGE_TYPE> PAGE_TYPE { get; set; }
    }
}
